theme: ./theme

markdown:
  headings:
    permalink: true

permalinks:
  page: /:slug.html
  post: /:slug.html


siteConfig:
  title: LengSword
  url: https://ylsword-cheat.top
  author: LengSword
  email: LengSword@gmail.com

themeConfig:
  nav:
    - text: Home
      link: /
    - text: Friends
      link: /friends.html
    - text: About
      link: /about.html
  social:
    rss: false
  utterances:
    repo: LengSword/blog
    theme: icy-dark

plugins:
  - resolve: saber-plugin-query-posts
  - resolve: saber-plugin-prismjs
  - resolve: saber-plugin-code-copy
    options:
      buttonStyle:
        border: none
  - resolve: saber-plugin-git-modification-time
  # - resolve: saber-plugin-feed
  #   options:
  #     atomFeed: false
